In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [4]:
坐标list = [[1,0],[1,1],[0,0]]
坐标arr = array(坐标list)
坐标list
坐标arr

array([[1, 0],
       [1, 1],
       [0, 0]])

In [5]:
x = 坐标arr[:,0]
x

array([1, 1, 0])

In [8]:
y = 坐标arr[:,1]
y

array([0, 1, 0])

In [9]:
a=zeros((9,9))
a.shape

(9, 9)

In [10]:
a[0,4]=1
a[0]

array([0., 0., 0., 0., 1., 0., 0., 0., 0.])